version: '3.8'

services:
  db:
    image: mysql:9.0.1
    container_name: AutenticacionDB
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: AutenticacionDB
    ports:
      - "3306:3306"
    networks:
      - app-network

  fastapi:
    build: .
    container_name: MicroservicioAutenticacion
    environment:
      - DATABASE_URL=mysql+pymysql://root:12345@db:3306/AutenticacionDB
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  app-network:
    driver: bridge